/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.motorph_cp2;

import java.awt.Color;
import main.java.motorph_employee.EmployeeInformation;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
class MotorPHGui extends javax.swing.JFrame implements EmployeeInformationPopulator {

    /**
     * Creates new form MotorPHGui
     */
    public MotorPHGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        EmpNumLbl = new javax.swing.JLabel();
        EmpNumTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        FNameLbl = new javax.swing.JLabel();
        BdayLbl = new javax.swing.JLabel();
        PhoneLbl = new javax.swing.JLabel();
        AddressLbl = new javax.swing.JLabel();
        SSSLbl = new javax.swing.JLabel();
        PHealthLbl = new javax.swing.JLabel();
        LNameLbl = new javax.swing.JLabel();
        TinLbl = new javax.swing.JLabel();
        PagibigLbl = new javax.swing.JLabel();
        StatusLbl = new javax.swing.JLabel();
        PositionLbl = new javax.swing.JLabel();
        SupervisorLbl = new javax.swing.JLabel();
        BaseSalaryLbl = new javax.swing.JLabel();
        RiceSubLbl = new javax.swing.JLabel();
        PhoneAllowLbl = new javax.swing.JLabel();
        ClotheAllowLbl = new javax.swing.JLabel();
        GrossSemMonthLbl = new javax.swing.JLabel();
        HourlyRateLbl = new javax.swing.JLabel();
        LNameTxt = new javax.swing.JTextField();
        FNameTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        SSSTxt = new javax.swing.JTextField();
        StatusTxt = new javax.swing.JTextField();
        SupervisorTxt = new javax.swing.JTextField();
        BaseSalaryTxt = new javax.swing.JTextField();
        PhoneAllowTxt = new javax.swing.JTextField();
        GrossSemMonthTxt = new javax.swing.JTextField();
        BdayTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        PositionTxt = new javax.swing.JTextField();
        RiceSubTxt = new javax.swing.JTextField();
        ClotheAllowTxt = new javax.swing.JTextField();
        HourlyRateTxt = new javax.swing.JTextField();
        PHealthTxt = new javax.swing.JTextField();
        TINTxt = new javax.swing.JTextField();
        PagibigTxt = new javax.swing.JTextField();
        ErrorPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 600));
        setResizable(false);

        TitleLbl.setBackground(new java.awt.Color(51, 51, 255));
        TitleLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbl.setText("MotorPH Employee Details");
        TitleLbl.setOpaque(true);

        EmpNumLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpNumLbl.setText("Employee Number");
        EmpNumLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EmpNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNumTxtActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.setFocusable(false);
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchBtnMouseExited(evt);
            }
        });
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        FNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FNameLbl.setText("First Name");
        FNameLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        BdayLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BdayLbl.setText("Birthdate");
        BdayLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PhoneLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneLbl.setText("Phone Number");
        PhoneLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddressLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressLbl.setText("Address");
        AddressLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SSSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSSLbl.setText("SSS Number");
        SSSLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PHealthLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PHealthLbl.setText("PhilHealth Number");
        PHealthLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        LNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LNameLbl.setText("Last Name");
        LNameLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        TinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TinLbl.setText("TIN Number");
        TinLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PagibigLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PagibigLbl.setText("Pag-ibig Number");
        PagibigLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        StatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLbl.setText("Status");
        StatusLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PositionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PositionLbl.setText("Position");
        PositionLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SupervisorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SupervisorLbl.setText("Immediate Supervisor");
        SupervisorLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        BaseSalaryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BaseSalaryLbl.setText("Basic Salary");
        BaseSalaryLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        RiceSubLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RiceSubLbl.setText("Rice Subsidy");
        RiceSubLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PhoneAllowLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneAllowLbl.setText("Phone Allowance");
        PhoneAllowLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ClotheAllowLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClotheAllowLbl.setText("Clothing Allowance");
        ClotheAllowLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        GrossSemMonthLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrossSemMonthLbl.setText("Gross Semi-monthly Rate");
        GrossSemMonthLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        HourlyRateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourlyRateLbl.setText("Hourly Rate");
        HourlyRateLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        LNameTxt.setEditable(false);

        FNameTxt.setEditable(false);

        AddressTxt.setEditable(false);

        SSSTxt.setEditable(false);

        StatusTxt.setEditable(false);

        SupervisorTxt.setEditable(false);

        BaseSalaryTxt.setEditable(false);

        PhoneAllowTxt.setEditable(false);

        GrossSemMonthTxt.setEditable(false);

        BdayTxt.setEditable(false);

        PhoneTxt.setEditable(false);

        PositionTxt.setEditable(false);

        RiceSubTxt.setEditable(false);
        RiceSubTxt.setToolTipText("");

        ClotheAllowTxt.setEditable(false);

        HourlyRateTxt.setEditable(false);

        PHealthTxt.setEditable(false);

        TINTxt.setEditable(false);

        PagibigTxt.setEditable(false);

        javax.swing.GroupLayout ErrorPanelLayout = new javax.swing.GroupLayout(ErrorPanel);
        ErrorPanel.setLayout(ErrorPanelLayout);
        ErrorPanelLayout.setHorizontalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        ErrorPanelLayout.setVerticalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PhoneAllowLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GrossSemMonthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(GrossSemMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(HourlyRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PhoneAllowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ClotheAllowLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ClotheAllowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BaseSalaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BaseSalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(RiceSubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RiceSubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(369, 369, 369)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(SupervisorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(SupervisorTxt))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EmpNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(AddressTxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SSSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SSSTxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PHealthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(PHealthTxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TINTxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(FNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(FNameTxt))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(EmpNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PhoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BdayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(SearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PositionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PagibigLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(StatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StatusTxt)
                                        .addComponent(PagibigTxt)
                                        .addComponent(PositionTxt)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(253, 253, 253)))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(ErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameLbl)
                    .addComponent(BdayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLbl)
                    .addComponent(PhoneLbl)
                    .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLbl)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSSLbl)
                    .addComponent(SSSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHealthLbl)
                    .addComponent(PHealthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinLbl)
                    .addComponent(TINTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PagibigLbl)
                    .addComponent(PagibigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLbl)
                    .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PositionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PositionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupervisorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupervisorLbl))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RiceSubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RiceSubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaseSalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaseSalaryLbl))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClotheAllowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClotheAllowLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneAllowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneAllowLbl))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HourlyRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrossSemMonthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrossSemMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(578, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        populateEmployeeInformation();
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void EmpNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNumTxtActionPerformed
        populateEmployeeInformation();
    }//GEN-LAST:event_EmpNumTxtActionPerformed

    private void SearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseEntered
        SearchBtn.setBackground(Color.white);
    }//GEN-LAST:event_SearchBtnMouseEntered

    private void SearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseExited
        SearchBtn.setBackground(Color.white);
    }//GEN-LAST:event_SearchBtnMouseExited
@Override
    public void populateEmployeeInformation() {
        try {
            int employeeNumber = Integer.parseInt(EmpNumTxt.getText());

            // Retrieve employee information
            List<String> employeeInfo = new EmployeeInformation().showEmployeeInformation(employeeNumber);

            // Populate text fields with employee details
            LNameTxt.setText(employeeInfo.get(0));
            FNameTxt.setText(employeeInfo.get(1));
            BdayTxt.setText(employeeInfo.get(2));
            AddressTxt.setText(employeeInfo.get(3));
            PhoneTxt.setText(employeeInfo.get(4));
            SSSTxt.setText(employeeInfo.get(5));
            PHealthTxt.setText(employeeInfo.get(16));
            TINTxt.setText(employeeInfo.get(7));
            PagibigTxt.setText(employeeInfo.get(8));
            StatusTxt.setText(employeeInfo.get(9));
            PositionTxt.setText(employeeInfo.get(10));
            SupervisorTxt.setText(employeeInfo.get(11));
            BaseSalaryTxt.setText(employeeInfo.get(12));
            RiceSubTxt.setText(employeeInfo.get(13));
            PhoneAllowTxt.setText(employeeInfo.get(14));
            ClotheAllowTxt.setText(employeeInfo.get(15));
            GrossSemMonthTxt.setText(employeeInfo.get(16));
            HourlyRateTxt.setText(employeeInfo.get(17));
        } catch (IOException | ParseException | NumberFormatException | NullPointerException e) {
            // Handle exceptions by showing an error message
            JOptionPane.showMessageDialog(ErrorPanel, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Displays an error dialog with the provided error message.
     *
     * @param errorMessage The message to be displayed in the error dialog.
     */
    public void showErrorDialog(String errorMessage) {
        JOptionPane.showMessageDialog(ErrorPanel, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorPHGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorPHGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorPHGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPHGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotorPHGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel BaseSalaryLbl;
    private javax.swing.JTextField BaseSalaryTxt;
    private javax.swing.JLabel BdayLbl;
    private javax.swing.JTextField BdayTxt;
    private javax.swing.JLabel ClotheAllowLbl;
    private javax.swing.JTextField ClotheAllowTxt;
    private javax.swing.JLabel EmpNumLbl;
    private javax.swing.JTextField EmpNumTxt;
    private javax.swing.JPanel ErrorPanel;
    private javax.swing.JLabel FNameLbl;
    private javax.swing.JTextField FNameTxt;
    private javax.swing.JLabel GrossSemMonthLbl;
    private javax.swing.JTextField GrossSemMonthTxt;
    private javax.swing.JLabel HourlyRateLbl;
    private javax.swing.JTextField HourlyRateTxt;
    private javax.swing.JLabel LNameLbl;
    private javax.swing.JTextField LNameTxt;
    private javax.swing.JLabel PHealthLbl;
    private javax.swing.JTextField PHealthTxt;
    private javax.swing.JLabel PagibigLbl;
    private javax.swing.JTextField PagibigTxt;
    private javax.swing.JLabel PhoneAllowLbl;
    private javax.swing.JTextField PhoneAllowTxt;
    private javax.swing.JLabel PhoneLbl;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel PositionLbl;
    private javax.swing.JTextField PositionTxt;
    private javax.swing.JLabel RiceSubLbl;
    private javax.swing.JTextField RiceSubTxt;
    private javax.swing.JLabel SSSLbl;
    private javax.swing.JTextField SSSTxt;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JLabel SupervisorLbl;
    private javax.swing.JTextField SupervisorTxt;
    private javax.swing.JTextField TINTxt;
    private javax.swing.JLabel TinLbl;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables

}
